# Generated by Django 5.0.4 on 2024-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi buyurtma"),
                            ("ready", "Dostavkaga tayyor"),
                            ("waiting", "Yetkazilmoqda"),
                            ("delivered", "Yetkazildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="new",
                        max_length=9,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Viloyatni tanlang", "Viloyatni tanlang"),
                            ("tashkent", "Toshkent shahar"),
                            ("andijon", "Andijon viloyati"),
                            ("buxoro", "Buxoro viloyati"),
                            ("fargona", "Fargʻona viloyati"),
                            ("jizzax", "Jizzax viloyati"),
                            ("namangan", "Namangan viloyati"),
                            ("navoiy", "Navoiy viloyati"),
                            ("qashqadaryo", "Qashqadaryo viloyati"),
                            ("qoraqalpogiston", "Qoraqalpogʻiston Respublika"),
                            ("samarqand", "Samarqand viloyati"),
                            ("sirdaryo", "Sirdaryo viloyati"),
                            ("surxondaryo", "Surxondaryo viloyati"),
                            ("toshkent", "Toshkent viloyati"),
                            ("xorazm", "Xorazm viloyati"),
                        ],
                        max_length=17,
                    ),
                ),
                ("phone_number", models.CharField(max_length=13)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
