# Generated by Django 5.0.6 on 2024-05-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
