name: Library Backend

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3  # Обновленная версия checkout
            - name: Set up Python 3.12
              uses: actions/setup-python@v4  # Обновленная версия setup-python
              with:
                python-version: "3.12"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests
              run: |
                python -m unittest discover
